### ISSUE TITLE
Text in the extension pages is invisible

### ISSUE THREAD

**Issue by CharoSW** [overdodactyl/userContent-tweaks#5]
The description text of most if not all extensions is invisible due to the text and background color being the same.  This affects Nightly at least but probably the others as well

**Comment by overdodactyl** [comment]
Hi @CharoSW,

Thanks for opening up the issue.  The issue appears to be arising due to some extensions using only some or none of the Firefox default styling and instead using css files built into the extension.

I've addressed the current "workaround" [here](https://github.com/overdodactyl/userContent-tweaks#important-update-11292017). 

In addition, please see #6.

**Comment by overdodactyl** [comment]
@CharoSW, also, please pull the latest update.  I did make an omission in the original userContent.css file that could have caused what you are talking about.

Let me know if that fixed it for you

**Comment by CharoSW** [comment]
the settings text wasn't what I was talking about, even though it is broken for some I did somewhat expect that.  what I was talking about was this: 
![backgroundtext](https://user-images.githubusercontent.com/19259975/33412134-a4fa2cec-d5dd-11e7-8bb9-032db076cfb1.png)
I've highlighted some of the text to show what I mean.  Your latest update didn't seem to fix it

**Comment by overdodactyl** [comment]
Thanks for the screenshot! That was the omission I was talking about in the second comment.  I _think_ that should now be fixed with the latest update.

**Comment by CharoSW** [comment]
I am an idiot, I pulled but it wasn't successful so the usercontent file hadn't updated.  It seems to be all working now

**Comment by overdodactyl** [comment]
Glad it's working now! :)
