### ISSUE TITLE
Windows user feedback.

### ISSUE THREAD

**Issue by chinook77** [overdodactyl/userContent-tweaks#8]
Hi, leaving feedback for dark theme on FF 57.0.1 x64 on windows 10. The only issues that I've found so far are:  

- the connection details sub-menu background color makes unable to read the text
![screenshot 31 _li](https://user-images.githubusercontent.com/19517348/33526243-f5363b10-d81c-11e7-9d1d-8abca6041491.jpg)

- a white horizontal line on the right context menu
![screenshot 30 _li](https://user-images.githubusercontent.com/19517348/33526170-a8fdca66-d81b-11e7-8243-471928a71099.jpg)

Thanks for your work.
Best regards.

**Comment by CaptaPraelium** [comment]
Just to add to this, I have the same issue with the download list in the toolbar, as above with the connection details.
The library (CTRL+J) is all-white.
Can confirm that white line.
Happy to contribute any code or testing as required.

**Comment by overdodactyl** [comment]
Hi @chinook77, thanks for the feedback, it's really appreciated!

The connections sub-menu was overlooked on my part (it's also not correct on macOS), so that will be fixed ASAP.

@CaptaPraelium, I believe that the download drop down issue [should now be resolved](https://github.com/overdodactyl/userContent-tweaks/blob/master/changelog.md#1232017-518-utc) - can you let me know if the latest version is ok?

In regards to the white line occurring on the context menu, can either of you tell what that is coming from?

It's not appearing on my mac, so it's hard to troubleshoot unfortunately

**Comment by overdodactyl** [comment]
Update: connection panel should be fixed (at least in terms of readability).

I'm debating whether I should change the color of FF's default secure connection color (green) to match the color scheme used in this repository (by default, darkcyan).  If anyone has any opinions/preferences, please let me know.

**Comment by chinook77** [comment]
"In regards to the white line occurring on the context menu, can either of you tell what that is coming from?"
I think because of this grey separator:
![screenshot 36 _li](https://user-images.githubusercontent.com/19517348/33531013-454bdc06-d866-11e7-9611-53effaeb689b.jpg)

**Comment by CaptaPraelium** [comment]
Connection properties and download toolbar looking great, thank you. That was quick.

I think it would be great to see the green replaced with the user's colour scheme.

Not sure where that white line is coming from but it may help to mention that it is actually not white but the light grey colour from your scripts. It is interesting to note that, we still have the separator shown by chinook, in addition to the grey line... But the grey line covers the full width of the menu as the separator used to, and now the separator at the top there is shorter like the others.

**Comment by overdodactyl** [comment]
Glad it's working!

I was thinking it should be changed too (I've changed it on my own browser), I just don't want to be to invasive with my changes.

But, then again, for those that don't like it, all they would have to do is remove a single `@import` line.  

I'll try and get a fix out soon for the context menus - I know those don't look great for you guys

**Comment by CaptaPraelium** [comment]
They do now! Nice work.

By the way, I highly recommend this with the https://github.com/m-khvoinitsky/dark-background-light-text-extension. There are other 'dark mode' extensions, but this one allows you to make a custom colour scheme.

I have noticed a few minor inconsistencies with the firefox dark theme but I'll make new bugs for those ASAP.

**Comment by overdodactyl** [comment]
Hi @CaptaPraelium,

I'm glad they're looking better!

Thanks for the heads up about that extension, I'm excited to give it a try.

As always, I appreciate the feedback.  If possible, please submit each bug/inconsistency you notice as it's own issue (makes it easier to keep track of everything and ensures the Issue feed only consists of ongoing/unaddressed problems) :)

**Comment by overdodactyl** [comment]
Resolved - 7503a89 and 512e490

**Comment by chinook77** [comment]
Hi, this separator It's back. How to remove it?
![screenshot 13 _li](https://user-images.githubusercontent.com/19517348/36031140-7bdf89d2-0d88-11e8-8358-5c106c862163.jpg)
Thanks in advance.

**Comment by overdodactyl** [comment]
Hi @chinook77, check out issue #60...there's a FF 58 bug that I believe is causing it to return.  The current workaround is to use the windows version of userChrome linked there.

Let me know if that fixes things for you.

**Comment by chinook77** [comment]
Thanks, that works.
